### ISSUE TITLE
Tried to use this, now I can no longer access my forum at all

### ISSUE THREAD

**Issue by MostHated** [julianlam/nodebb-plugin-sso-wordpress#9]
Hey there,
    I just tried to set this up, I put in my client/secret and hit save and let the board rebuild and restart, now I just get "Internal Server Error" and my Docker logs show: 

```error
Failed to lookup view "categories" in views directory "/usr/src/app/build/public/templates" {"view":{"defaultEngine":"tpl","ext":".tpl","name":"categories","root":"/usr/src/app/build/public/templates"},"stack":"Error: Failed to lookup view \"categories\" in views directory \"/usr/src/app/build/public/templates\"\n    at Function.render (/usr/src/app/node_modules/express/lib/application.js:580:17)\n    at ServerResponse.render (/usr/src/app/node_modules/express/lib/response.js:1008:7)\n    at content (/usr/src/app/src/middleware/render.js:84:15)\n    at /usr/src/app/node_modules/async/dist/async.js:3880:24\n    at replenish (/usr/src/app/node_modules/async/dist/async.js:1011:17)\n    at /usr/src/app/node_modules/async/dist/async.js:1016:9\n    at eachOfLimit (/usr/src/app/node_modules/async/dist/async.js:1041:24)\n    at /usr/src/app/node_modules/async/dist/async.js:1046:16\n    at eachOf (/usr/src/app/node_modules/async/dist/async.js:1117:5)\n    at _parallel (/usr/src/app/node_modules/async/dist/async.js:3879:5)"}
nodebb      | Error: Failed to lookup view "header" in views directory "/usr/src/app/build/public/templates"
nodebb      |     at Function.render (/usr/src/app/node_modules/express/lib/application.js:580:17)
nodebb      |     at /usr/src/app/src/middleware/header.js:222:13
nodebb      |     at nextTask (/usr/src/app/node_modules/async/dist/async.js:5324:14)
nodebb      |     at next (/usr/src/app/node_modules/async/dist/async.js:5331:9)
nodebb      |     at /usr/src/app/node_modules/async/dist/async.js:969:16
nodebb      |     at /usr/src/app/src/middleware/header.js:214:4
nodebb      |     at /usr/src/app/node_modules/async/dist/async.js:473:16
nodebb      |     at next (/usr/src/app/node_modules/async/dist/async.js:5329:29)
nodebb      |     at /usr/src/app/node_modules/async/dist/async.js:969:16
nodebb      |     at done (/usr/src/app/src/plugins/hooks.js:95:5)
```

I am fairly new to using this board, so I am not sure how I would even manually remove this plugin?

Thanks,
-MH

**Comment by MostHated** [comment]
Searching the forum, I was able to find the command ./nodebb reset -t, which looks like it at least got me back into the admin panel. Are you planning on updating this plugin anytime soon by chance? I just happened to look at the date of it's last commit and I didn't realize it was so old.

**Comment by julianlam** [comment]
`./nodebb reset -p sso-wordpress` should disable the plugin. However the issue sounds more like the templates didn't build, in which case a `./nodebb build` would get you up and running again.

**Comment by MostHated** [comment]
Would that mean that the plugin might still work, it was something else that messed up when I saved my info in there and then rebuilt/restarted?

**Comment by julianlam** [comment]
Yes, that'd be my guess at this time. The stack trace provided doesn't indicate an issue with the WordPress SSO plugin.
